namespace Test;
public class TestClassNullableProperties
{
    public double? Property0 { get; set; }
    public double? Property1 { get; set; }
    public double? Property2 { get; set; }
    public double? Property3 { get; set; }
    public double? Property4 { get; set; }
    public double? Property5 { get; set; }
    public double? Property6 { get; set; }
    public double? Property7 { get; set; }
    public double? Property8 { get; set; }
    public double? Property9 { get; set; }
    public double? Property10 { get; set; }
    public double? Property11 { get; set; }
    public double? Property12 { get; set; }
    public double? Property13 { get; set; }
    public double? Property14 { get; set; }
    public double? Property15 { get; set; }
    public double? Property16 { get; set; }
    public double? Property17 { get; set; }
    public double? Property18 { get; set; }
    public double? Property19 { get; set; }
    public double? Property20 { get; set; }
    public double? Property21 { get; set; }
    public double? Property22 { get; set; }
    public double? Property23 { get; set; }
    public double? Property24 { get; set; }
    public double? Property25 { get; set; }
    public double? Property26 { get; set; }
    public double? Property27 { get; set; }
    public double? Property28 { get; set; }
    public double? Property29 { get; set; }
    public double? Property30 { get; set; }
    public double? Property31 { get; set; }
    public double? Property32 { get; set; }
    public double? Property33 { get; set; }
    public double? Property34 { get; set; }
    public double? Property35 { get; set; }
    public double? Property36 { get; set; }
    public double? Property37 { get; set; }
    public double? Property38 { get; set; }
    public double? Property39 { get; set; }
    public double? Property40 { get; set; }
    public double? Property41 { get; set; }
    public double? Property42 { get; set; }
    public double? Property43 { get; set; }
    public double? Property44 { get; set; }
    public double? Property45 { get; set; }
    public double? Property46 { get; set; }
    public double? Property47 { get; set; }
    public double? Property48 { get; set; }
    public double? Property49 { get; set; }
    public double? Property50 { get; set; }
    public double? Property51 { get; set; }
    public double? Property52 { get; set; }
    public double? Property53 { get; set; }
    public double? Property54 { get; set; }
    public double? Property55 { get; set; }
    public double? Property56 { get; set; }
    public double? Property57 { get; set; }
    public double? Property58 { get; set; }
    public double? Property59 { get; set; }
    public double? Property60 { get; set; }
    public double? Property61 { get; set; }
    public double? Property62 { get; set; }
    public double? Property63 { get; set; }
    public double? Property64 { get; set; }
    public double? Property65 { get; set; }
    public double? Property66 { get; set; }
    public double? Property67 { get; set; }
    public double? Property68 { get; set; }
    public double? Property69 { get; set; }
    public double? Property70 { get; set; }
    public double? Property71 { get; set; }
    public double? Property72 { get; set; }
    public double? Property73 { get; set; }
    public double? Property74 { get; set; }
    public double? Property75 { get; set; }
    public double? Property76 { get; set; }
    public double? Property77 { get; set; }
    public double? Property78 { get; set; }
    public double? Property79 { get; set; }
    public double? Property80 { get; set; }
    public double? Property81 { get; set; }
    public double? Property82 { get; set; }
    public double? Property83 { get; set; }
    public double? Property84 { get; set; }
    public double? Property85 { get; set; }
    public double? Property86 { get; set; }
    public double? Property87 { get; set; }
    public double? Property88 { get; set; }
    public double? Property89 { get; set; }
    public double? Property90 { get; set; }
    public double? Property91 { get; set; }
    public double? Property92 { get; set; }
    public double? Property93 { get; set; }
    public double? Property94 { get; set; }
    public double? Property95 { get; set; }
    public double? Property96 { get; set; }
    public double? Property97 { get; set; }
    public double? Property98 { get; set; }
    public double? Property99 { get; set; }
}
