namespace Records;

public class Record0 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record1 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record2 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record3 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record4 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record5 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record6 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record7 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record8 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record9 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record10 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record11 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record12 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record13 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record14 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record15 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record16 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record17 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record18 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record19 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record20 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record21 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record22 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record23 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record24 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record25 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record26 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record27 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record28 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record29 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record30 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record31 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record32 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record33 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record34 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record35 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record36 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record37 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record38 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record39 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record40 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record41 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record42 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record43 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record44 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record45 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record46 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record47 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record48 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record49 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record50 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record51 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record52 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record53 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record54 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record55 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record56 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record57 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record58 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record59 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record60 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record61 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record62 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record63 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record64 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record65 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record66 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record67 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record68 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record69 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record70 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record71 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record72 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record73 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record74 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record75 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record76 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record77 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record78 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record79 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record80 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record81 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record82 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record83 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record84 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record85 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record86 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record87 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record88 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record89 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record90 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record91 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record92 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record93 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record94 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record95 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record96 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record97 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record98 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public class Record99 { string? A { get; set; } int B { get; set; } long C { get; set; } }