namespace Records;

public record Record0 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record1 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record2 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record3 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record4 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record5 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record6 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record7 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record8 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record9 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record10 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record11 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record12 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record13 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record14 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record15 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record16 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record17 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record18 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record19 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record20 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record21 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record22 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record23 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record24 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record25 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record26 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record27 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record28 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record29 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record30 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record31 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record32 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record33 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record34 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record35 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record36 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record37 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record38 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record39 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record40 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record41 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record42 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record43 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record44 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record45 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record46 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record47 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record48 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record49 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record50 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record51 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record52 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record53 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record54 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record55 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record56 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record57 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record58 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record59 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record60 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record61 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record62 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record63 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record64 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record65 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record66 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record67 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record68 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record69 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record70 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record71 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record72 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record73 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record74 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record75 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record76 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record77 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record78 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record79 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record80 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record81 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record82 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record83 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record84 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record85 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record86 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record87 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record88 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record89 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record90 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record91 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record92 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record93 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record94 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record95 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record96 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record97 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record98 { string? A { get; set; } int B { get; set; } long C { get; set; } }
public record Record99 { string? A { get; set; } int B { get; set; } long C { get; set; } }